home/urls.py
from django.conf.urls import url

from home.views.home import HomeView, AboutView
from home.views.login import LoginView
from home.views.logout import LogoutView
from home.views.register import RegisterView


app_name = 'home'
urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout')
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^stories/', include('story.urls'))
]

story/urls.py
from django.conf.urls import url

from story.views.stories import StoryListView
from story.views.page import PageView


app_name = 'story'
urlpatterns = [
    url(r'^$', StoryListView.as_view(), name='stories'),
    url(r'(?P<story>[\w-]+)/(?P<page>\w+)/', PageView.as_view(), name='page')
]

home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

story/models.py
from __future__ import unicode_literals

from django.db import models


class Story(models.Model):
    """ Story model """
    title = models.CharField(max_length=50)
    date_published = models.DateField(auto_now_add=True)
    slug = models.SlugField()


class Page(models.Model):
    """ Page model """
    story = models.ForeignKey(
        to='story.Story',
        related_name='pages'
    )
    number = models.PositiveIntegerField()
    content = models.TextField()

    class Meta:
        """ meta """
        unique_together = ('story', 'number')

home/forms/login.py
from django import forms


class LoginForm(forms.Form):
    """ login form """

    username = forms.CharField(max_length=32)
    password = forms.CharField(
        max_length=32,
        widget=forms.PasswordInput
    )

home/forms/register.py
from django import forms
from django.contrib.auth.models import User

class RegistrationForm(forms.ModelForm):
    """ registration form """

    class Meta:
        model = User
	fields = [
		'username',
		 'password', 
		'first_name', 
		'last_name', 
		'email'
	]

home/views.py
from django.views.generic.base import TemplateView

# Create your views here

class HomeView(TemplateView):
    """ Home page view """

    template_name = 'home/home.html'

    def get_context_data(self, **kwargs):
        """ context data """
        context = super(HomeView, self).get_context_data(**kwargs)
        return context

class AboutView(TemplateView):
    """ About page view """

    template_name = "home/about.html"

    def get_context_data(self, **kwargs):
        """ context data """
        context = super(AboutView, self).get_context_data(**kwargs)
        return context

home/views/home.py
from django.views.generic.base import TemplateView

# Create your views here

class HomeView(TemplateView):
    """ Home page view """

    template_name = 'home/home.html'

    def get_context_data(self, **kwargs):
        """ context data """
        context = super(HomeView, self).get_context_data(**kwargs)
        return context

class AboutView(TemplateView):
    """ About page view """

    template_name = "home/about.html"

    def get_context_data(self, **kwargs):
        """ context data """
        context = super(AboutView, self).get_context_data(**kwargs)
        return context

home/views/login.py
from __future__ import absolute_import, unicode_literals
from django.shortcuts import render
from django.views import View
from django.contrib.auth import (
    authenticate,
    login
)
from django.http import HttpResponseRedirect

from home.forms.login import LoginForm


class LoginView(View):
    """ login view """
    template_name = 'home/login.html'

    def get(self, request, *args, **kwargs):
        """ get handler """
        context = {'form': LoginForm()}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """ post handler """
        
        form = LoginForm(data=request.POST)
	context = {'form': form}

        if form and form.is_valid():
            user = authenticate(
                username=form.cleaned_data.get('username', ''),
                password=form.cleaned_data.get('password', '')
            )

            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/')
        return render(request, self.template_name, context)

home/views/logout.py
from django.contrib.auth import logout
from django.views import View
from django.http import HttpResponseRedirect


class LogoutView(View):
    """ logout view """

    def get(self, request, *args, **kwargs):
        """ get handler """
        if request.user.is_authenticated:
            logout(request)
        return HttpResponseRedirect('/')

home/views/register.py
from __future__ import absolute_import, unicode_literals
from django.views.generic.edit import FormView

from home.forms.register import RegistrationForm


class RegisterView(FormView):
    """ registration view """
    
    template_name = 'home/register.html'
    form_class = RegistrationForm
    success_url = '/'

    def form_valid(self, form):
        """ form valid override """
        form.save()
        return super(RegisterView, self).form_valid(form)

story/views/page.py
from django.views import View
from django.http import HttpResponseRedirect
from django.shortcuts import render

from story.models import Page


class PageView(View):
    """ page view """

    template_name = 'story/page.html'

    def get(self, request, *args, **kwargs):
        """ get handler """
        page_number = kwargs.get('page')
        story = kwargs.get('story')

        try:
            page = Page.objects.select_related(
                'story'
            ).get(
                story__slug=story,
                number=page_number
            )
        except Page.DoesNotExist:
            return HttpResponseRedirect('/stories/')
        
        context = {
            'page': page,
            'story': page.story,
            'has_next': page_number < page.story.pages.count(),
            'has_previous': page_number > 1
        }
        return render(request, self.template_name, context)

story/views/stories.py
from django.views.generic.list import ListView

from story.models import Story


class StoryListView(ListView):
    """ stories list """
    model = Story
    template_name = 'story/stories.html'

home/templates/home/about.html
{% extends "base.html" %}

{% block content %}
About page
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}

{% block content %}
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consequat mi ipsum, nec interdum risus ornare interdum. Aliquam iaculis enim eget purus vehicula fringilla. Vestibulum ac dictum nulla. In et imperdiet ex. Praesent ac odio et felis rhoncus porttitor. Nullam sit amet cursus lectus. Nullam a dictum urna, vitae egestas erat. Morbi in euismod ex.
Integer elementum, nisl sit amet ultrices pharetra, lacus nisl feugiat diam, at bibendum ante nulla a risus. Nulla quis metus sollicitudin, hendrerit ex ut, varius lectus. Donec feugiat volutpat ex vitae blandit. Curabitur dapibus aliquam odio non vehicula. Etiam laoreet turpis id neque blandit gravida. Aenean viverra eros leo. Quisque a nisl rutrum, faucibus est eu, pellentesque lorem.
Fusce pharetra pharetra arcu non tincidunt. Praesent commodo dolor velit, nec placerat erat luctus a. Cras eget est id neque gravida laoreet. In varius semper lorem, at posuere est laoreet at. Nulla blandit, eros eu pulvinar volutpat, ante ante consequat mauris, quis ultricies arcu massa ac ligula. Mauris odio est, imperdiet vitae scelerisque sit amet, gravida id nulla. Nulla sit amet vulputate lectus. Etiam sit amet justo rhoncus, suscipit tortor nec, posuere tellus. Pellentesque lectus lectus, cursus ut finibus a, lobortis ac justo. Proin nisl neque, porttitor eget mauris sit amet, hendrerit tincidunt odio. Curabitur tortor ante, consequat eget laoreet quis, feugiat eget sapien. Ut imperdiet euismod quam, sed dignissim lorem gravida porttitor. In hac habitasse platea dictumst. Sed scelerisque a ex vitae ornare.
Etiam sed ornare dolor. Fusce sit amet ligula sit amet ligula convallis faucibus. Vivamus rutrum in ipsum vel posuere. Morbi tempus, nunc eu facilisis sagittis, mi ex posuere ipsum, eget mollis enim dolor sit amet lacus. Duis est lectus, blandit non tempor ac, pretium eget elit. Praesent lobortis vulputate rhoncus. Sed gravida nisi non erat interdum, at hendrerit est ultrices. Nulla facilisi. Etiam sem enim, tristique in nulla nec, lobortis vehicula sem. Integer sit amet vulputate leo. Praesent sit amet mi pellentesque nisi tempus sagittis vel nec justo.
Aliquam pellentesque laoreet diam, non suscipit ligula vehicula quis. In sagittis est metus, nec lacinia felis condimentum tempus. Maecenas accumsan iaculis justo, non hendrerit dolor condimentum ac. Nullam blandit erat nec suscipit mollis. Sed venenatis velit vitae nulla blandit, eget gravida est varius. Curabitur congue lacinia lacinia. Vivamus mattis velit felis, eget lacinia urna aliquam sit amet. Proin iaculis felis id dictum aliquam. Mauris molestie mollis leo, et elementum sem semper fringilla. Sed at dui ex. Cras placerat nisl tortor, id aliquam elit luctus in. Nullam tellus orci, malesuada a lobortis at, egestas a nulla. Praesent tempus eget elit quis pharetra. Phasellus at maximus mi. 
{% endblock %}

home/templates/home/login.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'home:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="submit" />
</form>

{% endblock %}

home/templates/home/register.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'home:register' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="submit" />
</form>

{% endblock %}

story/templates/story/page.html
{% extends 'base.html' %}

{% block content %}
{{ page.number }}
{{ page.content }}

{% if has_previous %}
<a href="{% url 'story:page' story=story.slug page=page.number|add:"-1" %}" >Previous</a>
{% endif %}

<a href="{% url 'story:stories' %}" >Home</a>

{% if has_next %}
<a href="{% url 'story:page' story=story.slug page=page.number|add:"1" %}" >Next</a>
{% endif %}

{% endblock %}

story/templates/story/stories.html
{% extends 'base.html' %}

{% block content %} 
<br/>
<ul>
{% for story in object_list %}
   <li>
   {{ story.title }} - {{ story.date_published }}
   <br/>
   <a href="{% url 'story:page' story=story.slug page=1 %}">Read</a>
   </li>
{% empty %}
    <li>No Stories yet.</li>
{% endfor %}
</ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Whitleys World</title>
		<link href="https://fonts.googleapis.com/css?family=Amaranth" rel="stylesheet"> 
		 <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet"> 
		<style type="text/css">
			html, body {
            	height: 100%;
            	margin: 0px;
            	padding: 0px;
        	}
        	h1 {
 			   margin-top: 0;
			}
			.outer{
				min-height: 100%;
			}	
			.inner {
  				width:100%;
			}
			.content{
				min-height:100%;
			}
			.wrapperBanner {
				width: 80%;
				height: 100%;
				min-height: 70px;
    			margin: 0 auto;
    			background-color: #ff9438;
    			border-left: 1px dashed #FFDE00;
    			border-right: 1px dashed #FFDE00;
			}
			.contentWrapper{
				width: 80%;
				height: 100%;
				min-height: 100%;
    			margin: 0 auto;
			}
			.headerBorder{
				border-bottom: 1px dashed #FFDE00;
				background-color: #097054;
			}
			.footerBorder{
				background-color: #097054;
				border-top: 1px dashed #FFDE00;
			}
			#header{
				min-height: 70px;
			}
			#footer{
				min-height: 70px;
			}
			.nav{
				margin: 0;
				padding-top: 10px;
			}
			#nav li {
				float: left;
				padding: 10px;
				list-style: none;
			}
			.links{
				font-family: 'Amaranth', sans-serif;
				text-decoration:none;
				color: #6599FF;
			}
			.contentText{
				font-family: 'Josefin Sans', sans-serif;
				margin: 0px 30px 30px 30px;
				padding-top: 30px;
			}
			.headerImg{
				padding: 20px;
				margin-left: 50px;
			}
		</style>
		<!--[if lte IE 6]>
	    <style type="text/css">
        	.outer {
            	height: 100%;
        	}
    	</style>
    	<![endif]-->
	</head>
	<body>
		<div id='page' class='outer'> 
			<div id='header' class='inner headerBorder'>
				<div id='headerBanner' class='wrapperBanner'>
					<img src='' alt='whitleys-world' class='headerImg'/>
					<br/>
					<ul id='nav' class='nav'>
						<li><a href="{% url 'home:home' %}" class='links'>Home</a></li>
						<li><a href="{% url 'story:stories' %}" class='links'>Stories</a></li>
						<li><a href="{% url 'home:about' %}" class='links'>About</a></li>
                                                {% if user.is_authenticated %}
                                                	<li><a href="{% url 'home:logout' %}" class="links">Logout</a></li>
                                                {% else %}
                                                	<li><a href="{% url 'home:login' %}" class="links">Login</a></li>
                                                	<li><a href="{% url 'home:register' %}" class="links">Register</a></li>
                                                {% endif %}
					</ul>
				</div>
			</div>
			<div id='content' class='inner content'>
				<div class='contentWrapper'>
					<div class='contentText'>
						{% block content %}{% endblock content %}
					</div>
				</div>
			</div>
			<div id='footer' class='inner footerBorder'>
				<div id='footerBanner' class='wrapperBanner'>
				<span style="color: grey; font-weight: lighter; font-size:75%; float:right; padding: 10px;">Created by: The Blob Works Ltd.</span>
				</div>
			</div>	
		</div>
	</body>
</html>